# Generated by Django 6.0.6 on 2026-06-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='gdrive_url',
            field=models.URLField(blank=True, help_text='Link to Google Drive documents', null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository/PR', null=True),
        ),
    ]
