# Generated by Django 6.0.6 on 2026-06-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gdrive_url',
            field=models.URLField(blank=True, help_text='Link to Google Drive folder (containing Requirement, Design, Implementation, Testing, Deployment)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to GitHub repository', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('AUTOMATION', 'Automation'), ('PRODUCT', 'Product Development'), ('SECURITY', 'Cyber Security'), ('AI', 'AI Platform'), ('RESEARCH', 'Research'), ('INTERNAL', 'Internal'), ('AGENTIC_AI', 'Agentic AI')], max_length=20),
        ),
    ]
