# Generated by Django 6.0.6 on 2026-07-06 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_gdrive_url_project_github_url_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('AUTOMATION', 'Automation'), ('PRODUCT', 'Product Development'), ('SECURITY', 'Cyber Security'), ('AI', 'AI Platform'), ('RESEARCH', 'Research'), ('INTERNAL', 'Internal'), ('AGENTIC_AI', 'Agentic AI'), ('AUTOMOTIVE', 'Automotive')], max_length=20),
        ),
    ]
