# Generated by Django 6.0.6 on 2026-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_team_alter_project_project_type'),
        ('teams', '0003_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='projects', to='teams.team'),
        ),
    ]
