# Generated by Django 6.0.6 on 2026-08-04 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='client_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('CONVERTED', 'Converted to Tasks'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
