# Generated by Django 6.0.6 on 2026-08-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_requirement_effort_spent_requirement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
