# Generated by Django 6.0.6 on 2026-08-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_requirement_requirement_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='requirement_type',
            new_name='phase',
        ),
        migrations.AddField(
            model_name='requirement',
            name='dependency',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
