# Generated by Django 6.0.6 on 2026-07-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_news_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='interested_topics',
            field=models.CharField(blank=True, help_text='Comma-separated topics of interest', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='news_last_fetched',
            field=models.DateField(blank=True, null=True),
        ),
    ]
