# Generated by Django 6.0.6 on 2026-07-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noteentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='core.notetopic'),
        ),
    ]
