# Generated by Django 6.0.6 on 2026-07-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_note_topic'),
        ('teams', '0003_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='core_users', through='teams.TeamMember', through_fields=('user', 'team'), to='teams.team'),
        ),
    ]
