# Generated by Django 6.0.6 on 2026-08-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
