# Generated by Django 5.2.4 on 2026-09-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Ongoing / Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ONGOING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="lms.course",
                    ),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        blank=True, related_name="mentor_batches", to="lms.lmsuser"
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="student_batches", to="lms.lmsuser"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "code"],
            },
        ),
        migrations.CreateModel(
            name="StudentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "title",
                    models.CharField(default="Tuition & Course Fee", max_length=255),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid / Verified"),
                            ("PARTIAL", "Partially Paid"),
                            ("PENDING", "Pending / Unpaid"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived / Scholarship"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("UPI", "UPI / QR Code"),
                            ("BANK_TRANSFER", "Bank Transfer / NEFT / IMPS"),
                            ("CREDIT_DEBIT_CARD", "Credit / Debit Card"),
                            ("CASH", "Cash / Direct"),
                            ("ONLINE", "Online Gateway"),
                            ("OTHER", "Other"),
                        ],
                        default="UPI",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="UTR / UPI Txn ID / Reference Number",
                        max_length=255,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_number", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="lms.batch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="lms.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="lms.lmsuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
