# Generated by Django 5.2.4 on 2026-09-14 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_batch_studentpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("scheduled_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("meeting_link", models.URLField(help_text="Google Meet / Zoom URL")),
                (
                    "recording_link",
                    models.URLField(
                        blank=True,
                        help_text="Session recording URL if completed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("LIVE", "Live / In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                (
                    "agenda",
                    models.TextField(
                        blank=True,
                        help_text="Topics and lab objectives for this session",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lms.batch",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_sessions",
                        to="lms.lmsuser",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BatchMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("SLIDES", "Slide Deck / Presentation"),
                            ("CODE_REPO", "Source Code / GitHub Repo"),
                            ("DOCUMENT", "Lecture Notes / Document"),
                            ("RECORDING", "Class Video Recording"),
                            ("ASSIGNMENT", "Lab Assignment / Exercise"),
                            ("ATTACHMENT", "File Attachment / Download"),
                            ("OTHER", "Other Resource"),
                        ],
                        default="DOCUMENT",
                        max_length=30,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Drive, GitHub, or Colab link", null=True
                    ),
                ),
                (
                    "attachment_file",
                    models.FileField(
                        blank=True, null=True, upload_to="batch_materials/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="lms.batch",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lms.lmsuser",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materials",
                        to="lms.batchsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
