# Generated by Django 5.2.4 on 2026-09-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_batchsession_batchmaterial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="gdrive_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Google Drive folder URL or path",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="github_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GitHub repository URL or path",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="schedule",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Repetitive schedule summary",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="schedule_days",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Repetitive schedule days, e.g., Mon, Wed, Fri",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="schedule_time",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Schedule time, e.g., 18:00 - 20:00",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="zoom_link",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Zoom / Google Meet recurring meeting link",
                max_length=500,
            ),
        ),
    ]
