# Generated by Django 5.2.4 on 2026-09-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_batchassignment_sessionattendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchAssignmentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending / Not Graded"),
                            ("GRADED", "Graded / Assessed"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="GRADED",
                        max_length=20,
                    ),
                ),
                ("mentor_feedback", models.TextField(blank=True)),
                ("submission_url", models.URLField(blank=True, null=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_batch_assessments",
                        to="lms.lmsuser",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="lms.batchassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_assignment_assessments",
                        to="lms.lmsuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("assignment", "student"),
                        name="unique_batch_assignment_student_assessment",
                    )
                ],
            },
        ),
    ]
