# Generated by Django 5.2.4 on 2026-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_mentormessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="github_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific GitHub file or directory path within the repository",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="batchassignmentassessment",
            name="github_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific GitHub file or directory path within the repository",
                max_length=500,
            ),
        ),
    ]
