# Generated by Django 5.2.4 on 2026-09-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_assignmentsubmission_github_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the student last opened a chapter in this course",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Last chapter/lesson opened by the student in this course",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_opened_enrollments",
                to="lms.lesson",
            ),
        ),
    ]
