# Generated by Django 5.2.4 on 2026-09-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_enrollment_last_accessed_at_enrollment_last_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="mcq_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether all MCQs in this chapter were attempted",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="mcq_score",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of MCQs answered correctly"
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="mcq_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="mcq_total",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of MCQs in this chapter"
            ),
        ),
    ]
