# Generated by Django 5.2.4 on 2026-09-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_lessonprogress_mcq_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchsession",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated batch assignment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_sessions",
                to="lms.batchassignment",
            ),
        ),
        migrations.AddField(
            model_name="batchsession",
            name="assignment_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the assignment or homework task",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="batchsession",
            name="assignment_url",
            field=models.URLField(
                blank=True,
                help_text="Direct link or GitHub repo for this session's assignment",
                null=True,
            ),
        ),
    ]
