# Generated by Django 6.0.6 on 2026-08-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_requirement'),
        ('tasks', '0002_task_gdrive_url_task_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.requirement'),
        ),
    ]
