# Generated by Django 6.0.6 on 2026-08-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
