# Generated by Django 6.0.6 on 2026-08-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_hours_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('MAINTENANCE', 'Maintenance')], default='DEVELOPMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('IN_REVIEW', 'In Review'), ('TESTING', 'Testing'), ('PENDING_APPROVAL', 'Pending Approval'), ('BLOCKED', 'Blocked'), ('CLOSED', 'Closed')], default='BACKLOG', max_length=20),
        ),
    ]
